Report test results
Signed-off-by: Michael Carroll <mjcarroll@intrinsic.ai>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,6 +16,18 @@ jobs:
           codecov-enabled: true
           cpplint-enabled: true
           doxygen-enabled: true
+      - name: Strip workspace prefix
+        if: success() || failure() # always run even if the previous step fails
+        run: |
+          mkdir test_results/
+          cp ./build/test_results/*.xml ./test_results/
+          sed -i 's+/github/workspace/++g' ./test_results/*.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          check_name: 'Ubuntu Focal Results'
+          report_paths: 'build/test_results/*.xml'
   jammy-ci:
     runs-on: ubuntu-latest
     name: Ubuntu Jammy CI
@@ -25,3 +37,15 @@ jobs:
       - name: Compile and test
         id: ci
         uses: gazebo-tooling/action-gz-ci@jammy
+      - name: Strip workspace prefix
+        if: success() || failure() # always run even if the previous step fails
+        run: |
+          mkdir test_results/
+          cp ./build/test_results/*.xml ./test_results/
+          sed -i 's+/github/workspace/++g' ./test_results/*.xml
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          check_name: 'Ubuntu Jammy Results'
+          report_paths: 'test_results/*.xml'
